name: setup Flutter & Packages & Codegen
description: "Install and cache Flutter, Packages, Codegen"
runs:
  using: "composite"
  steps:
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        cache: true

    - name: 'Cache pubspec dependencies'
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.FLUTTER_HOME }}/.pub-cache
          **/.packages
          **/.flutter-plugins
          **/.flutter-plugin-dependencies
          **/.dart_tool/package_config.json
        key: build-pubspec-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          build-pubspec-

    - name: Cache build runner
      uses: actions/cache@v4
      with:
        path: |
          **/.dart_tool/build
        key: build-runner-${{ hashFiles('**/asset_graph.json') }}-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          build-runner-

    - name: Initialize
      shell: bash
      run: make init
